---
- name: 创建redis安装目录
  file: path={{ redis_dir }} owner=root group=root state=directory
- name: 拷贝redis安装包
  copy: src=/etc/ansible/redis-cluster/roles/redis/files/redis-3.2.11.tar.gz dest=/tmp
- name: 解压redis安装包
  shell: chdir=/tmp tar -xf redis-3.2.11.tar.gz -C {{ redis_dir }}
- name: 编译安装redis
  shell: chdir=/data/redis-3.2.11 make && make install
- name: 创建redis集群目录
  shell: chdir={{ redis_dir }}  mkdir -pv redis_cluster/{7000..7002}
- name: 模版redis配置文件
  template: src=redis.conf.j2 dest=/data/redis_cluster/7000/redis.conf
- name: 拷贝redis.conf到redis集群7001目录下
  shell: cp /data/redis_cluster/7000/redis.conf /data/redis_cluster/7001/
- name: 拷贝redis.conf到redis集群7002目录下
  shell: cp /data/redis_cluster/7000/redis.conf /data/redis_cluster/7002/
- name: 修改redis配置文件并启动redis
  script: /etc/ansible/redis-cluster/roles/redis/files/redis_config.sh
- name: 拷贝ruby安装包
  copy: src=/etc/ansible/redis-cluster/roles/redis/files/ruby-2.5.1.tar.gz dest=/tmp
- name: 解压ruby安装包
  shell: chdir=/tmp tar -xf ruby-2.5.1.tar.gz -C {{ redis_dir }}
- name: 编译安装ruby
  shell: chdir=/data/ruby-2.5.1 ./configure && make && make install
- name: ruby gem安装
  shell: gem install redis
- name: 创建redis cluster
  shell: chdir=/data/redis-3.2.11/src  echo yes | ./redis-trib.rb create --replicas 1 {{ redis1 }}:7000 {{ redis1 }}:7001 {{ redis1 }}:7002 {{ redis2 }}:7000 {{ redis2 }}:7001 {{ redis2 }}:7002
  when: "ansible_eth0['ipv4']['address']  == '{{ redis1 }}'"
- name: 关闭redis
  shell: pkill redis
- name: 添加访问密码后启动redis
  script: /etc/ansible/redis-cluster/roles/redis/files/redis_add_pass.sh
- name: 开机启动设置
  shell: echo "/usr/local/bin/redis-server /data/redis_cluster/{{ item }}/redis.conf" >> /etc/rc.local
  with_items:
     - 7000
     - 7001
     - 7002
...
