---
- hosts: redis_cluster
  remote_user: root
  tasks: 
  - name: 拷贝redis安装包
    copy: src=/ansible/soft/redis-3.2.11.tar.gz dest=/data/
  - name: 解压redis安装包
    shell: chdir=/data tar -xf redis-3.2.11.tar.gz
  - name: 编译安装redis
    shell: chdir=/data/redis-3.2.11 make && make install
  - name: 创建redis集群目录
    shell: chdir=/data/ mkdir -pv redis_cluster/{7000..7002}
  - name: 模版redis配置文件
    template: src=/ansible/template/redis.conf.j2 dest=/data/redis_cluster/7000/redis.conf
  - name: 拷贝redis.conf到redis集群7001目录下
    shell: cp /data/redis_cluster/7000/redis.conf /data/redis_cluster/7001/
  - name: 拷贝redis.conf到redis集群7002目录下
    shell: cp /data/redis_cluster/7000/redis.conf /data/redis_cluster/7002/
  - name: 修改redis配置文件并启动redis
    script: /ansible/scripts/redis.sh
  - name: 拷贝ruby安装包
    copy: src=/ansible/soft/ruby-2.5.1.tar.gz dest=/data/
  - name: 解压ruby安装包
    shell: chdir=/data tar -xf ruby-2.5.1.tar.gz
  - name: 编译安装ruby
    shell: chdir=/data/ruby-2.5.1 ./configure && make && make install
  - name: ruby gem安装
    shell: gem install redis
...
